[package]
name = "sd-networkd-wg-deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
curve25519-dalek = "4.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tar = "0.4.41"
