[package]
name = "sd-networkd-wg-deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
base64 = "0.22.1"
curve25519-dalek = "4.1.2"
ipnet = { version = "2.9", features = ["serde"] }
rand = "0.8.5"
serde = "1.0.203"
serde_yaml = "0.9.34"
x25519-dalek = "2.0.1"
